[opener]
play = [
	{ run = "mpv %s", orphan = true, for = "unix" },
]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
	{ run = "xdg-open %s", desc = "Open" },
]
imv = [
  { run = "imv-wayland %s", orphan = true, desc = "imv" },
]
zathura = [
  { run = "zathura %s", orphan = true, desc = "pdf viewer" }
]

[open]
prepend_rules = [
    { mime = "image/*", use = "imv" },
    { mime = "application/pdf", use = "zathura" }
]
