unbind r
bind r source-file ~/.tmux.conf \; display-message "Config updated"

set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g mouse on
#set -g status-position top
#set -g status-justify absolute-centre

#set -g status-style "bg=#0e1013"
#set -g message-style "bg=#0e1013,fg=blue,bold"
#set -g message-command-style "bg=blue,fg=#0e1013,bold"
#set -g window-status-current-style "fg=blue bold"
#set -g status-right "TMUX"
#set -g status-left "#S"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind -n M-H previous-window
bind -n M-L next-window

# =--------- Plugins ----------
# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-status-right "#S"
set -g @minimal-tmux-status-left "TMUX"
run '~/.tmux/plugins/tpm/tpm'
