#!/bin/sh

$HOME/Scripts/random-wallpaper.sh &
#wbg -s $HOME/Pictures/wallpapers/nix_01.png &
$HOME/Scripts/low_battery.sh &
brightnessctl set 40%

case "$(hostname)" in
  nixos-home) 
    wlr-randr --output DP-2 --mode 1920x1080@165Hz
    solaar -w hide & ;; 
  nixos-NV15)
    wlr-randr --output HDMI-A-2 --mode 1920x1080@144.001007Hz --pos 0,0
    wlr-randr --output eDP-1 --mode 1920x1080@165Hz --right-of HDMI-A-2
    solaar -w hide & ;; 
  nixos-T480)
    wlr-randr --output HDMI-A-2 --mode 1920x1080@120Hz --pos 0,0
    wlr-randr --output eDP-1 --right-of HDMI-A-2
esac

swayidle \
  timeout 1800 'waylock -ignore-empty-password -init-color 0x282727 -input-color 0x2b3328 -fail-color 0x43242b' \
  timeout 3600 'systemctl suspend' &

gammastep -l 15.87:100.99 -m wayland -b 1:0.9 &

synology-drive &

# QT_QPA_PLATFORM QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE QT_PLUGIN_PATH GTK_THEME

exec dbus-update-activation-environment --systemd \
  DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots 
