# -*- conf[main]
[main]
#include=/usr/share/foot/themes/nvim-dark
shell=zsh
term=foot
locked-title=no
font=JetBrainsMonoNerdFontMono:size=13,monospace:size=13
line-height=20
letter-spacing=0.2
pad=20x10
[environment]
[security]
osc52=enabled
[bell]
[desktop-notifications]
[scrollback]
[url]
[cursor]
style=block
blink=no
[mouse]
[touch]
[colors-dark]
alpha=0.9
cursor=181616 c5c9c5 # SumiInk3 DragonWhite
foreground=c5c9c5 # DragonWhite
background=181616 # SumiInk3

selection-background=393836 # SumiInk5
selection-foreground=c5c9c5 # DragonWhite

regular0=0d0c0c # SumiInk0
regular1=c4746e # DragonRed
regular2=8a9a7b # DragonGreen
regular3=dca561 # AutumnYellow
regular4=8ba4b0 # DragonBlue
regular5=a292a3 # DragonPink
regular6=8ea4a2 # DragonAqua
regular7=c5c9c5 # DragonWhite

bright0=a6a69c # DragonGray
bright1=c4746e # DragonRed
bright2=87a987 # DragonGreen2
bright3=dca561 # AutumnYellow
bright4=8ba4b0 # DragonBlue
bright5=a292a3 # DragonPink
bright6=8ea4a2 # DragonAqua
bright7=181616 # SumiInk3
[csd]
[key-bindings]
[search-bindings]
[url-bindings]
[text-bindings]
[mouse-bindings]
