playback_state = "Playing"
backend = "pulseaudio"
use_nerdfont = true
notify = true
default_keybindings = true
shuffle = true
library_tabs = [ "playlists", "albums", "artists", "podcasts", "browse" ]
[theme]
background = "#0D0C0C"
primary = "#C5C9C5"
secondary = "#a6a69c"
title = "#8ea4a2"
playing = "#8a9a7b"
playing_selected = "#8a9a7b"
playing_bg = "#181616"
highlight = "#8ba4b0"
highlight_bg = "#0D0C0C"
error = "#c4746e"
error_bg = "#43242b"
statusbar = "#8ea4a2"
statusbar_progress = "#8a9a7b"
statusbar_bg = "#0d0c0c"
cmdline = "#8a9a7b"
cmdline_bg = "#282727"
