# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cpp\
$rust\
$python\
$sudo\
$character"""

[os]
disabled = false
format = "[   ]($style)"
style = "bold blue"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold white"

[directory]
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[c]
format = "[$symbol($version(-$name))]($style) "

[cpp]
format = "[$symbol($version)]($style) "

[rust]
format = "[$symbol($version)]($style) "

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[sudo]
format = "[$symbol]($style)"
symbol = "󰡗 "
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
