return {
  "nvim-telescope/telescope.nvim",
  cmd = "Telescope",
  dependencies = { "nvim-lua/plenary.nvim" },
  keys = {
    { "<leader>fh", "<cmd>Telescope help_tags<cr>", desc = "[F]ind [H]elp tags" },
    { "<leader>fk", "<cmd>Telescope keymaps<cr>", desc = "[F]ind [K]eymaps" },
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "[F]ind [F]iles" },
    { "<leader>fs", "<cmd>Telescope builtin<cr>", desc = "[F]ind [S]elect telescope" },
    { "<leader>fw", "<cmd>Telescope grep_string<cr>", desc = "[F]ind current [W]ord", mode = { "n", "v" } },
    { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "[F]ind by [G]rep" },
    { "<leader>fd", "<cmd>Telescope diagnostics<cr>", desc = "[F]ind [D]iagnostics" },
    { "<leader>fr", "<cmd>Telescope resume<cr>", desc = "[F]ind [R]esume" },
    { "<leader>f.", "<cmd>Telescope oldfiles<cr>", desc = '[F]ind recent files ("." for repeat)' },
    { "<leader><leader>", "<cmd>Telescope buffers<cr>", desc = "[F]ind existing buffers" },
    { "<leader>fm", "<cmd>Telescope man_pages<cr>", desc = "[F]ind [M]an Pages" },
    { "<leader>ft", "<cmd>Telescope treesitter<cr>", desc = "[F]ind [T]reesitter" },
    { "<leader>fc", "<cmd>Telescope colorscheme<cr>", desc = "[F]ind [C]olors" },
  },
  opts = {},
}
